name: Deploy to NGINX

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Pull Latest Changes
              run: |
                  cd /root/mbmil
                  ls -la
                  git pull origin main

            - name: Restart NGINX
              run: sudo systemctl restart nginx
