name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Change this to your main branch name, e.g., master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Copy HTML files to gh-pages branch
              run: |
                  git checkout --orphan gh-pages
                  git rm -rf .
                  cp -r $GITHUB_WORKSPACE/* .
                  git add .
                  git -c user.name='GitHub Actions' -c user.email='actions@github.com' commit -m 'Deploy HTML files to gh-pages'
                  git push origin gh-pages --force
